# Generated by Django 4.2.5 on 2023-11-03 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_title', models.CharField(default='', max_length=250)),
                ('playlist_logo', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(default='', max_length=250)),
                ('artist', models.CharField(default='', max_length=250)),
                ('song_logo', models.CharField(default='', max_length=250)),
                ('song_mp3', models.FileField(default='', upload_to='mp3/')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist')),
            ],
        ),
    ]
