# Generated by Django 4.2.5 on 2023-11-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist_playlist_subtitle_song_added_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MadeforyouPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_title', models.CharField(default='', max_length=250)),
                ('playlist_logo', models.CharField(default='', max_length=250)),
                ('playlist_subtitle', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RecentPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_title', models.CharField(default='', max_length=250)),
                ('playlist_logo', models.CharField(default='', max_length=250)),
                ('playlist_subtitle', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_title', models.CharField(default='', max_length=250)),
                ('playlist_logo', models.CharField(default='', max_length=250)),
                ('playlist_subtitle', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
