# Generated by Django 4.2.5 on 2023-11-05 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_madeforyouplaylist_recentplaylist_welcomeplaylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcomeplaylist',
            name='playlist_subtitle',
        ),
    ]
