# Generated by Django 4.2.5 on 2023-11-05 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_welcomeplaylist_playlist_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcomeplaylist',
            old_name='playlist_logo',
            new_name='playlist_subtitle',
        ),
    ]
